const translations = {
  en: {
    hero_eyebrow: "Welcome to",
    hero_sub: "Your private sanctuary above Dubrovnik",
    checkin_chip: "Check-in from 16:00",
    checkout_chip: "Check-out by 10:00",
    wifi_chip: "WiFi: lidija2023",
    hero_cta: "Explore the Guide",
    nav_arrival: "Arrival",
    nav_villa: "The Villa",
    nav_guide: "Guide",
    nav_addons: "Add-ons",
    nav_local: "Dubrovnik",
    nav_contact: "Contact",
    nav_departure: "Departure",
    arrival_title: "Arrival & Access",
    arrival_sub: "Everything you need for a smooth arrival.",
    map_title: "Getting Here",
    map_villa: "Villa Address",
    map_parking: "Parking Garage",
    map_parking_desc: "Ilijina glavica · ~10 min walk, flat route",
    map_dropoff: "Drop-off Point",
    map_dropoff_desc: "Villa not reachable by car — use nearest drop-off",
    map_btn_villa: "Directions to Villa",
    map_btn_parking: "Parking Garage",
    address_title: "Address",
    view_map: "View on Google Maps →",
    checkinout_title: "Check-in & Check-out",
    checkin_label: "Check-in",
    checkout_label: "Check-out",
    checkin_note: "Please inform your host of your expected arrival time so she can welcome you personally.",
    access_title: "Entrance",
    access_desc: "The entrance gate has a keypad on the right side. Your personal entry code will be sent to you by your host on the day of arrival.",
    access_badge: "Code sent on arrival day",
    parking_title: "Parking",
    parking_desc: "Parking is available at Best in Parking — Garaža Ilijina glavica, approximately 10 minutes walk from the villa along a flat route.",
    parking_link: "Get directions to parking →",
    luggage_title: "Getting to the Villa",
    luggage_desc: "The villa is located in a residential zone not accessible by car. The nearest drop-off point is a short walk away. If you need help with luggage, porter service is available — just let us know in advance.",
    dropoff_link: "View drop-off point →",
    host_title: "Your Host",
    host_desc: "Daniela is your dedicated contact throughout your stay, available on WhatsApp until 23:00 daily.",
    villa_title: "The Villa",
    villa_desc: "Set just minutes from Dubrovnik's UNESCO-listed Old Town, Majestic Villa Lidija is a 360m² private retreat spread across three floors, offering sweeping views of the Adriatic, the islands, and the medieval city walls.",
    feat_beds: "3 en-suite bedrooms",
    feat_guests: "Up to 6 guests",
    feat_pool: "Heated infinity pool",
    feat_sauna: "Sauna (master suite)",
    feat_gym: "Private gym",
    feat_view: "Sea & city views",
    feat_kitchen: "Fully equipped kitchen",
    feat_tv: "Smart TV in every room",
    villa_irundo_link: "View on irundo.com →",
    guide_title: "Villa Guide",
    acc_climate: "Climate & Comfort",
    cooling_title: "Air Conditioning",
    cooling_desc: "Ceiling air conditioners in every room, controlled via the TOSHIBA thermostat on the wall. Use the power button and adjust temperature with + / – buttons.",
    heating_title: "Floor Heating",
    heating_desc: "Each room has its own floor heating thermostat on the wall — a dial that shows the current temperature. Turn the dial to set your preferred warmth.",
    water_title: "Hot Water",
    water_desc: "Unlimited hot water from the boiler in the basement storage room (behind the gym). Tap water is safe to drink.",
    acc_tech: "Technology",
    wifi_title: "Wi-Fi",
    wifi_detail: "Network boosters are placed throughout the villa for full coverage.",
    wifi_network: "Network",
    wifi_password: "Password",
    tv_title: "Smart TV",
    tv_desc: "Smart TVs in the living room and all three bedrooms. Press the Home button on the remote to access apps and streaming services.",
    blinds_title: "Roof Blinds",
    blinds_desc: "Scan the QR code on the remote control, then select the direction of movement using the remote device.",
    intercom_title: "Intercom",
    intercom_desc: "Touchscreen intercom at the entrance. Use it to communicate with visitors at the gate.",
    acc_pool: "Pool & Sauna",
    pool_title: "Infinity Pool",
    pool_desc: "The heated infinity pool is cleaned once a week. If you'd like additional cleaning during your stay, just ask — no extra charge. Please supervise children at all times near the pool.",
    sauna_title: "Sauna",
    sauna_desc: "Located in the top-floor master bedroom. Turn on using the switch outside the sauna door. We recommend a short shower before use, stay well hydrated, and limit sessions to 10–15 minutes.",
    acc_kitchen: "Kitchen & Appliances",
    oven_title: "Oven",
    oven_desc: "Bosch HRA574BB0. The kitchen is fully equipped with hob, oven, dishwasher, fridge/freezer, coffee machine and smoothie maker.",
    oven_manual: "Oven manual →",
    washer_title: "Washing Machine & Dryer",
    washer_desc: "Separate washer and dryer in the basement storage room (with the gym). There is also an additional washing machine in the villa.",
    washer_manual: "Washer manual →",
    addons_title: "Add-ons & Experiences",
    addons_sub: "Enhance your stay. Submit a request and we'll arrange everything.",
    addon_chef: "Private Chef Experience",
    addon_grocery: "Grocery Pre-Stocking",
    addon_transfer: "Airport Transfer",
    addon_cleaning: "Additional Cleaning",
    addon_wine: "Wine & Sommelier",
    addon_boat: "Private Boat Trip",
    form_title: "Request a Service",
    form_select_hint: "Select a service from the left, or describe your request below.",
    form_name: "Full Name",
    form_email: "Email",
    form_date: "Preferred Date & Time",
    form_notes: "Notes / Special Requests",
    form_submit: "Send Request",
    form_success: "✓ Request sent! We'll be in touch shortly.",
    local_title: "Explore Dubrovnik",
    local_sub: "Our favourite spots, handpicked for your stay.",
    tab_beaches: "Beaches",
    tab_restaurants: "Restaurants",
    tab_sights: "Sights",
    tab_transport: "Transport",
    beach1_name: "Banje Beach",
    beach1_dist: "1.2 km — the closest beach with Old Town views",
    beach2_name: "Sveti Jakov Beach",
    beach2_dist: "2.1 km — secluded cove, accessible by steps",
    beach3_name: "Copacabana Beach",
    beach3_dist: "3.5 km — great for families, water sports",
    rest1_name: "Restaurant Nautika",
    rest1_desc: "Fine dining, terrace with sea views",
    rest2_name: "Restaurant 360°",
    rest2_desc: "Michelin-starred, on the city walls",
    rest3_name: "Proto",
    rest3_desc: "Seafood institution in the Old Town",
    rest4_name: "Konzum & Tommy",
    rest4_desc: "Nearest supermarkets, 0.8–1.2 km",
    sight1_name: "Old Town Walls",
    sight1_desc: "2.5 km — UNESCO-listed city walls walk",
    sight2_name: "Fort Lovrijenac",
    sight2_desc: "3.0 km — the city's freestanding fortress",
    sight3_name: "Cable Car Srđ",
    sight3_desc: "2.8 km — panoramic views over the entire city",
    trans1_name: "Dubrovnik Airport (DBV)",
    trans1_desc: "Official airport website & arrivals",
    trans2_name: "Eko Taxi",
    trans2_desc: "Reliable local taxi service",
    trans3_name: "Libertas Bus",
    trans3_desc: "Local bus routes around Dubrovnik",
    trans4_name: "Jadrolinija Ferry",
    trans4_desc: "Ferry connections to nearby islands",
    trans5_name: "Luggage Storage",
    trans5_desc: "Secure luggage storage in the city",
    contact_title: "Get in Touch",
    contact_sub: "We're here to make your stay perfect.",
    contact_wa_title: "WhatsApp",
    contact_wa_sub: "Fastest response — message us directly",
    contact_call_title: "Call Us",
    contact_email_title: "Email",
    emergency_title: "🚨 Emergency Numbers",
    emerg_eu: "European Emergency",
    emerg_police: "Police",
    emerg_fire: "Fire",
    emerg_hospital: "Hospital Dubrovnik",
    departure_title: "Departure",
    departure_sub: "We hope you had an unforgettable stay.",
    dep1_title: "Check out by 10:00 AM",
    dep1_desc: "Please contact Daniela the day before departure to confirm your check-out time.",
    dep2_title: "Keys & Access",
    dep2_desc: "Leave all keys, remotes and access items in the villa before you leave.",
    dep3_title: "Luggage Storage",
    dep3_desc: "Need to store bags after check-out? Luggage storage and porter service are available on request.",
    dep4_title: "Leave a Review",
    dep4_desc: "Your feedback means the world to us. If you enjoyed your stay, please consider leaving a review on Booking.com or Airbnb.",
    farewell_text: "We hope Dubrovnik left a mark on your heart. We'd love to welcome you back.",
    farewell_btn: "Book your next stay →",
    footer_text: "© 2025 Irundo · Majestic Villa Lidija · irundo.com",
  }
};

// i18n engine
let currentLang = localStorage.getItem('villa_lang') || 'en';

// HR and DE — copy of EN as placeholder; replace with translations when ready
translations.hr = { ...translations.en,
  hero_eyebrow: "Dobrodošli u",
  hero_sub: "Vaše privatno utočište iznad Dubrovnika",
  checkin_chip: "Check-in 16:00–21:00",
  checkout_chip: "Check-out do 10:00",
  wifi_chip: "WiFi: lidija2023",
  hero_cta: "Istražite vodič",
  nav_arrival: "Dolazak",
  nav_villa: "Vila",
  nav_guide: "Vodič",
  nav_addons: "Usluge",
  nav_local: "Dubrovnik",
  nav_contact: "Kontakt",
  nav_departure: "Odlazak",
  arrival_title: "Dolazak & pristup",
  arrival_sub: "Sve što trebate za nesmetan dolazak.",
  address_title: "Adresa",
  view_map: "Pogledaj na Google Mapsu →",
  checkinout_title: "Check-in & Check-out",
  checkin_label: "Check-in",
  checkout_label: "Check-out",
  checkin_note: "Molimo obavijestite domaćicu o očekivanom vremenu dolaska.",
  access_title: "Ulaz",
  access_desc: "Ulazna vrata imaju tipkovnicu s desne strane. Osobni kod za ulaz poslat će vam domaćica na dan dolaska.",
  access_badge: "Kod šalje domaćica na dan dolaska",
  parking_title: "Parkiranje",
  parking_desc: "Parkiranje je moguće u garaži Best in Parking — Garaža Ilijina glavica, oko 10 minuta hoda po ravnom.",
  parking_link: "Upute do parkirišta →",
  luggage_title: "Dolazak do ville",
  luggage_desc: "Vila se nalazi u stambenoj zoni nedostupnoj automobilom. Najbliže mjesto za iskrcaj je kratka šetnja dalje. Treba li vam pomoć s prtljagom? Dostupna je usluga nosača — samo nas unaprijed obavijestite.",
  dropoff_link: "Pogledaj mjesto iskrcaja →",
  host_title: "Vaša domaćica",
  host_desc: "Daniela je vaš kontakt tijekom cijelog boravka. Dostupna na WhatsAppu do 23:00 svakodnevno.",
  map_title: "Kako doći",
  map_villa: "Adresa ville",
  map_parking: "Garaža",
  map_parking_desc: "Ilijina glavica · ~10 min hoda, ravna ruta",
  map_dropoff: "Iskrcajno mjesto",
  map_dropoff_desc: "Vila nije dostupna automobilom — koristite najbliže iskrcajno mjesto",
  map_btn_villa: "Upute do ville",
  map_btn_parking: "Garaža",
  contact_title: "Kontaktirajte nas",
  contact_sub: "Tu smo da vaš boravak bude savršen.",
  contact_wa_title: "WhatsApp",
  contact_wa_sub: "Najbrži odgovor — pišite nam direktno",
  contact_call_title: "Nazovite nas",
  contact_email_title: "E-mail",
  emergency_title: "Hitni brojevi",
  emerg_eu: "Europski hitni poziv",
  emerg_police: "Policija",
  emerg_fire: "Vatrogasci",
  emerg_hospital: "Bolnica Dubrovnik",
  departure_title: "Odlazak",
  departure_sub: "Nadamo se da ste imali nezaboravan boravak.",
  dep1_title: "Check-out do 10:00",
  dep1_desc: "Molimo kontaktirajte Danielu dan prije odlaska radi potvrde.",
  dep2_title: "Ključevi & pristup",
  dep2_desc: "Ostavite sve ključeve, daljinske upravljače i pristupne predmete u vili.",
  dep3_title: "Čuvanje prtljage",
  dep3_desc: "Trebate čuvanje prtljage nakon check-outa? Dostupno na zahtjev.",
  dep4_title: "Ostavite recenziju",
  dep4_desc: "Vaša povratna informacija nam je važna. Razmislite o recenziji na Booking.com ili Airbnbu.",
  farewell_text: "Nadamo se da je Dubrovnik ostavio trag u vašem srcu. Radujemo se ponovnom susretu.",
  farewell_btn: "Rezervirajte sljedeći boravak →",
};

translations.de = { ...translations.en,
  hero_eyebrow: "Willkommen in",
  hero_sub: "Ihr privates Refugium über Dubrovnik",
  checkin_chip: "Check-in 16:00–21:00",
  checkout_chip: "Check-out bis 10:00",
  wifi_chip: "WLAN: lidija2023",
  hero_cta: "Guide entdecken",
  nav_arrival: "Anreise",
  nav_villa: "Die Villa",
  nav_guide: "Guide",
  nav_addons: "Services",
  nav_local: "Dubrovnik",
  nav_contact: "Kontakt",
  nav_departure: "Abreise",
  arrival_title: "Anreise & Zugang",
  arrival_sub: "Alles, was Sie für eine reibungslose Ankunft benötigen.",
  address_title: "Adresse",
  view_map: "Auf Google Maps anzeigen →",
  checkinout_title: "Check-in & Check-out",
  checkin_label: "Check-in",
  checkout_label: "Check-out",
  checkin_note: "Bitte informieren Sie Ihre Gastgeberin über Ihre voraussichtliche Ankunftszeit.",
  access_title: "Eingang",
  access_desc: "Das Eingangstor hat ein Tastenfeld auf der rechten Seite. Ihr persönlicher Zugangscode wird Ihnen von Ihrer Gastgeberin am Anreisetag zugeschickt.",
  access_badge: "Code wird am Anreisetag gesendet",
  parking_title: "Parken",
  parking_desc: "Parkmöglichkeit im Best in Parking — Garaža Ilijina glavica, ca. 10 Minuten Fußweg auf flacher Route.",
  parking_link: "Wegbeschreibung zum Parkhaus →",
  host_title: "Ihre Gastgeberin",
  host_desc: "Daniela ist Ihre Ansprechpartnerin während des gesamten Aufenthalts. Täglich bis 23:00 auf WhatsApp erreichbar.",
  map_title: "Anreise",
  map_btn_villa: "Wegbeschreibung zur Villa",
  map_btn_parking: "Parkhaus",
  contact_title: "Kontakt",
  contact_sub: "Wir sind für Sie da.",
  contact_wa_sub: "Schnellste Antwort — schreiben Sie uns direkt",
  emergency_title: "Notrufnummern",
  departure_title: "Abreise",
  departure_sub: "Wir hoffen, Sie hatten einen unvergesslichen Aufenthalt.",
  farewell_text: "Wir hoffen, dass Dubrovnik einen bleibenden Eindruck hinterlassen hat.",
  farewell_btn: "Nächsten Aufenthalt buchen →",
};

function applyTranslations(lang) {
  if (!translations[lang]) return;
  currentLang = lang;
  localStorage.setItem('villa_lang', lang);
  const t = translations[lang];
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (t[key]) el.textContent = t[key];
  });
  document.documentElement.lang = lang;
}

document.addEventListener('DOMContentLoaded', () => {
  applyTranslations(currentLang);
});
